### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by uspc17** [Cajoline/ticktick-linux#2]
Great job on making TickTick available to Linux users!

I'm using Debian Stretch's Firefox ESR browser with JavaScript but not Flash. When I try to log into the web version it doesn't even allow clicking on either "sign in" button.

It was the same with my phone's Firefox, but then I clicked on the help guide link through my app and am now using the web version on my phone, which looks great.

When I downloaded and executed this, it was just like the web version, so I could not log in either. Could you please help me in troubleshooting this issue, as I would like to use your app?

**Comment by Cajoline** [comment]
Hi,
to answer your question, this version of TickTick is simply an encapuslation of the web version with electron, which means that if you encounter connection problems with the web version you may encounter them with this version
